name: _surface-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - antlr-python-runtime >=4,<5
  - antlr >=4,<5
  - bokeh
  - giflib
  - jupyterlab_launcher
  - libpng
  - matplotlib
  - networkx
  - nodejs
  - notebook
  - pandas
  - pygraphviz
  - python >=3.6,<3.7
  - seaborn
  - setuptools
  - pip:
    - https://github.com/deathbeds/aye/archive/3cfdcecd7b8123917b2d22bd5acd50f2c54b19d1.tar.gz
    - https://github.com/sympy/sympy/archive/1e8b5da3edbdbfe23cb664e1fe4982d88133c9b9.tar.gz
