name: _surface-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - antlr-python-runtime >=4,<5
  - bokeh
  - click
  - giflib
  - hypothesis
  - jupyterlab_launcher
  - libpng
  - matplotlib
  - monkeytype
  - networkx
  - nodejs
  - notebook
  - pandas
  - pygraphviz
  - python >=3.6,<3.7
  - seaborn
  - setuptools
  - pip:
    - https://github.com/deathbeds/aye/archive/7a98066ac228c9449b1db5537db365198f6f84b9.tar.gz
    - https://github.com/sympy/sympy/archive/bbca46c3f1a2bfb4cfd2b09b70e503f3bba21b7e.tar.gz
