name: _surface-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - bqplot
  - ipyleaflet
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - pythreejs
  - pip:
    - rise
# SOON:    - https://github.com/deathbeds/XXX/archive/master.tar.gz
