name: _surface-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - bqplot
  - ipyleaflet
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - pythreejs
  - vaex
  - pip:
    - rise
    - https://github.com/deathbeds/XXX/archive/c3750c847ca13f56980f0c985fb08835afe663e2.tar.gz
