name: _ktop-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - bqplot
  - ipyleaflet
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - pythreejs
  - antlr-python-runtime
  - pip:
    - rise
