name: _surface-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - giflib
  - jupyterlab_launcher
  - libpng
  - matplotlib
  - networkx
  - nodejs
  - notebook
  - pandas
  - python >=3.6,<3.7
  - seaborn
  - setuptools
  - antlr-python-runtime
  - pygraphviz
  - pip:
    - git+https://github.com/deathbeds/aye@tests
    - https://github.com/bollwyvl/sympy/archive/feat/parse_latex.tar.gz
